### ISSUE TITLE
@Redirect conflict with carpet

### ISSUE THREAD

**Issue by antisoma** [DrexHD/ItsMine#1]
Hi,

I'm pretty new to Fabric and building mods.  But have managed to get ItsMine working on a test server.  However when I try to run ItsMine and Carpet at the same time the server fails to load.  The error is reported as:

```[14:19:50] [main/INFO]: [FabricLoader] Loading 4 mods: minecraft@1.17-alpha.20.51.a, itsmine@2.3.3-20w51a, fabricloader@0.10.8, carpet@1.4.21
[14:19:50] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/opt/minecraft/servers/snapback/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[14:19:55] [main/WARN]: @Redirect conflict. Skipping carpet.mixins.json:ServerPlayerInteractionManager_cactusMixin->@Redirect::activateWithOptionalCactus(Lnet/minecraft/class_2680;Lnet/minecraft/class_1937;Lnet/minecraft/class_1657;Lnet/minecraft/class_1268;Lnet/minecraft/class_3965;)Lnet/minecraft/class_1269; with priority 1000, already redirected by itsmine.mixins.json:ServerPlayerInteractionManagerMixin->@Redirect::interactIfPossible(Lnet/minecraft/class_2680;Lnet/minecraft/class_1937;Lnet/minecraft/class_1657;Lnet/mi[14:19:55] [main/INFO]: [STDERR]: java.lang.RuntimeException: Failed to setup Fabric server environment!
[14:19:55] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:52)
[14:19:55] [main/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred when launching the server!
[14:19:55] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:108)
[14:19:55] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50)
[14:19:55] [main/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: An exception occurred when launching the server!
[14:19:55] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:64)
[14:19:55] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106)
[14:19:55] [main/INFO]: [STDERR]: 	... 1 more```

**Comment by DrexHD** [comment]
This project is no longer maintained [ItsOurs](https://github.com/DrexHD/ItsOurs) is a rework of this mod. But both mods are specifically designed for my own server and I don't have time to provide support for it. You could try to remove the ServerPlayerInteractionManager_cactusMixin from carpet (since it isn't too useful).

**Comment by antisoma** [comment]
Thanks Drex.
